# Generated by Django 3.0.5 on 2020-06-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.TextField()),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Guild')),
            ],
        ),
    ]
