# Generated by Django 3.0.5 on 2020-06-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Guild'),
        ),
        migrations.AlterField(
            model_name='question',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Guild'),
        ),
    ]
